---
- name: Deploy Button Cricute App (Fix Filename)
  hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/fanfinfon/button_cricute.git"
    app_folder: "/home/pi/button_cricute"
    # UPDATED: Changed from .yaml to .yml
    compose_file: "{{ app_folder }}/docker-compose.yml" 

  tasks:
    - name: Ensure Git is installed
      apt: name=git state=present update_cache=yes

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_folder }}"
        version: main
        force: yes

    # --- DEBUG STEP: SEE THE FILES ---
    - name: List files in the folder (To check the name)
      shell: "ls -la {{ app_folder }}"
      register: file_list

    - name: Show me the files
      debug:
        msg: "The files in the folder are: {{ file_list.stdout_lines }}"

    # --- THE DETECTIVE ---
    - name: Find the real Arduino USB Port
      shell: "ls /dev/ttyACM* /dev/ttyUSB* 2>/dev/null | head -n 1"
      register: usb_device
      ignore_errors: yes

    - name: Fail if no Arduino is found
      fail:
        msg: "CRITICAL ERROR: No Arduino found plugged into USB!"
      when: usb_device.stdout == ""

    - name: Show what we found
      debug:
        msg: "Found Arduino at: {{ usb_device.stdout }}"

    # --- THE SURGEON (FIXED PATH) ---
    - name: Update docker-compose to use the REAL port
      replace:
        path: "{{ compose_file }}"
        regexp: '/dev/ttyACM0'
        replace: "{{ usb_device.stdout }}"

    - name: Update docker-compose to use Privileged Mode
      lineinfile:
        path: "{{ compose_file }}"
        insertafter: 'restart: unless-stopped'
        line: '    privileged: true'

    # --- STOP & START ---
    - name: Stop old container
      shell:
        cmd: "docker compose down"
        chdir: "{{ app_folder }}"
      ignore_errors: yes

    - name: Start Docker
      shell:
        cmd: "docker compose up -d --build"
        chdir: "{{ app_folder }}"